import Head from 'next/head'
import {useRouter} from 'next/router';
import { Box } from '@mui/material'
import { songs } from '../data/songs';
import styles from '../styles/Home.module.css'
// import Search from '../components/Search';
import MUICard from '../components/Card';

export default function Home() {
  const router = useRouter();
  const clickHandler = (songId) => {
    router.push(`localhost:3000/songs/${songId}`)
  };

  return (
    <>
       <Head>
        <title>Youtube Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
          <Box sx={{m:2}} className={styles.container}>
              <h1 className={styles.title}>
               Welcome to my YouTube search
            </h1>
          </Box>
      <Box sx={{m:2}}>
        {/* <Search/> */}
      </Box>
      {songs.map ((song)=> {
          return (
            <div key={song.id} onClick={()=>clickHandler(song.id)}>
                    <MUICard item={song}/>
            </div>            
          )
      })}     
    </Box>
    </>
  )
}
